<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <TargetFrameworks>net8.0</TargetFrameworks>
    <IsTestProject>true</IsTestProject>
    <NoWarn>$(NoWarn);RS1001;RS2008</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.14.0" />
    <ProjectReference Include="..\..\src\Zerberuz.Analyzers\Zerberuz.Analyzers.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
